import { db } from "./db";

export async function seedDatabase() {
  const existingUsers = await db("users").count("* as count");
  if (Number(existingUsers[0].count) > 0) return;

  const users = await db("users").insert([
    { username: "scott.foley", full_name: "Scott Foley", role: "cas_lead", email: "scott.foley@reasongroup.com" },
    { username: "alex.kocz", full_name: "Alex Kocz", role: "csd_lead", email: "alex.kocz@reasongroup.com" },
    { username: "mark.volpato", full_name: "Mark Volpato", role: "bid_manager", email: "mark.volpato@reasongroup.com" },
    { username: "anil.kinagi", full_name: "Anil Kinagi", role: "writer", email: "anil.kinagi@reasongroup.com" },
    { username: "rupa.tamang", full_name: "Rupa Tamang", role: "executive", email: "rupa.tamang@reasongroup.com" },
    { username: "sarah.chen", full_name: "Sarah Chen", role: "writer", email: "sarah.chen@reasongroup.com" },
    { username: "james.mitchell", full_name: "James Mitchell", role: "bid_manager", email: "james.mitchell@reasongroup.com" },
    { username: "priya.sharma", full_name: "Priya Sharma", role: "writer", email: "priya.sharma@reasongroup.com" },
  ]).returning("*");

  const opps = await db("opportunities").insert([
    {
      name: "ABS ServiceNow PPM & IRM 202504",
      phase: "1.A - Activity",
      value: 450000,
      margin: 0.25,
      work_type: "Delivery",
      vat: "GROWTH",
      status: "Risk",
      comment: "PPM and IRM Contract with SNOW, migration opportunity",
      cas_lead: "Scott Foley",
      csd_lead: "Alex Kocz",
      category: "Hunt;Partner",
      partner: "ServiceNow",
      client_contact: "Ian Scensor",
      client_code: "ABS",
    },
    {
      name: "ACR RFQ DOD WP3 Transition HR Modules",
      phase: "1.A - Activity",
      value: 1999992,
      margin: 0.27,
      work_type: "Resource Pool",
      vat: "GROWTH",
      status: "Risk",
      comment: "Recontest after no decision on PASSS, likely Infosys got extension",
      cas_lead: "Aleksandar Vranesevic",
      csd_lead: "Alex Kocz",
      category: "Hunt;ERP;Partner",
      partner: "Oracle;SAP",
      client_code: "PTR-Accenture",
    },
    {
      name: "Notice Enterprise Sustainability Platform 202511",
      phase: "1.A - Activity",
      work_type: "RFI/EOI",
      vat: "GROWTH",
      comment: "Advance notice only.",
      cas_lead: "Aleksandar Vranesevic",
      category: "Hunt",
      client_code: "ACT",
    },
    {
      name: "Defence Cloud Migration Program 2025",
      phase: "2.B - Qualified",
      value: 3500000,
      margin: 0.3,
      work_type: "Delivery",
      vat: "GROWTH",
      status: "Active",
      comment: "Large scale cloud migration for defence infrastructure",
      cas_lead: "Scott Foley",
      csd_lead: "Anil Kinagi",
      category: "Hunt;Cloud",
      partner: "AWS;Microsoft",
      client_code: "DEF",
    },
    {
      name: "Federal Data Analytics Platform RFP",
      phase: "1.A - Activity",
      value: 2100000,
      margin: 0.22,
      work_type: "Project",
      vat: "GROWTH",
      status: "New",
      comment: "Analytics platform modernization using Power BI and Azure",
      cas_lead: "Mark Volpato",
      csd_lead: "Alex Kocz",
      category: "Hunt;Analytics",
      partner: "Microsoft",
      client_code: "FED",
    },
    {
      name: "Telstra Network Transformation Phase 2",
      phase: "2.B - Qualified",
      value: 4200000,
      margin: 0.32,
      work_type: "Delivery",
      vat: "GROWTH",
      status: "Active",
      comment: "Phase 2 of network infrastructure transformation, SD-WAN rollout",
      cas_lead: "Scott Foley",
      csd_lead: "Alex Kocz",
      category: "Hunt;Cloud;Network",
      partner: "Cisco;AWS",
      client_contact: "Michael Torres",
      client_code: "TEL",
    },
    {
      name: "NAB Digital Banking Platform Uplift",
      phase: "1.A - Activity",
      value: 2800000,
      margin: 0.28,
      work_type: "Project",
      vat: "GROWTH",
      status: "New",
      comment: "Core banking platform modernisation with API-first architecture",
      cas_lead: "Mark Volpato",
      csd_lead: "Alex Kocz",
      category: "Hunt;Digital",
      partner: "Microsoft;Temenos",
      client_contact: "David Wong",
      client_code: "NAB",
    },
    {
      name: "Victoria Police Data Warehouse Modernisation",
      phase: "3.C - Shortlisted",
      value: 1750000,
      margin: 0.35,
      work_type: "Delivery",
      vat: "GROWTH",
      status: "Active",
      comment: "Migration from on-prem Oracle DW to Snowflake on Azure",
      cas_lead: "Scott Foley",
      csd_lead: "Anil Kinagi",
      category: "Hunt;Analytics;Cloud",
      partner: "Snowflake;Microsoft",
      client_contact: "Karen Liu",
      client_code: "VPL",
    },
    {
      name: "Woolworths SAP S/4HANA Migration",
      phase: "1.A - Activity",
      value: 8500000,
      margin: 0.2,
      work_type: "Delivery",
      vat: "GROWTH",
      status: "Risk",
      comment: "Enterprise-wide SAP ECC to S/4HANA migration, multi-year engagement",
      cas_lead: "Aleksandar Vranesevic",
      csd_lead: "Alex Kocz",
      category: "Hunt;ERP;Partner",
      partner: "SAP",
      client_contact: "Rachel Adams",
      client_code: "WOW",
    },
    {
      name: "BHP Cybersecurity Operations Centre",
      phase: "2.B - Qualified",
      value: 3100000,
      margin: 0.33,
      work_type: "Managed Service",
      vat: "GROWTH",
      status: "Active",
      comment: "24/7 SOC setup with SIEM/SOAR implementation using Splunk",
      cas_lead: "Scott Foley",
      csd_lead: "Alex Kocz",
      category: "Hunt;Security",
      partner: "Splunk;CrowdStrike",
      client_contact: "Tom Bradley",
      client_code: "BHP",
    },
  ]).returning("*");

  const bidEntries = await db("bids").insert([
    {
      opportunity_id: opps[3].id,
      title: "Defence Cloud Migration Program 2025",
      stage: "writing",
      cas_qualified: "qualified",
      csd_qualified: "qualified",
      bid_manager_id: users[2].id,
      assigned_writer_id: users[3].id,
      care_score: 7.5,
      competitive_position: 8,
      attractiveness: 9,
      relationship_strength: 6,
      ease_of_response: 7,
      care_analysis: "Strong competitive position with AWS/Microsoft partnership. Highly attractive deal with good margins. Moderate relationship - need to strengthen client engagement. Reasonable response timeline.",
    },
    {
      opportunity_id: opps[0].id,
      title: "ABS ServiceNow PPM & IRM 202504",
      stage: "cas_qualification",
      cas_qualified: "pending",
      csd_qualified: "pending",
    },
    {
      opportunity_id: opps[4].id,
      title: "Federal Data Analytics Platform RFP",
      stage: "executive_review",
      cas_qualified: "qualified",
      csd_qualified: "qualified",
      bid_manager_id: users[2].id,
      assigned_writer_id: users[3].id,
      care_score: 8,
      competitive_position: 8,
      attractiveness: 8,
      relationship_strength: 7,
      ease_of_response: 9,
      executive_approval: "pending",
      technical_response: "# Federal Data Analytics Platform\n\n## Executive Summary\nReason Group proposes a comprehensive analytics modernization platform leveraging Power BI, Azure Synapse Analytics, and modern data engineering practices.\n\n## Proposed Solution\nOur solution combines Azure Data Factory for ETL orchestration, Azure Synapse for unified analytics, and Power BI for visualization.\n\n## Implementation Approach\nAgile delivery over 6 sprints with dedicated cross-functional teams.",
      delivery_plan: "# Delivery Plan\n\n## Phase 1: Discovery (Weeks 1-4)\n- Requirements workshops\n- Data source assessment\n- Architecture design\n\n## Phase 2: Build (Weeks 5-16)\n- Data pipeline development\n- Dashboard creation\n- Integration testing\n\n## Phase 3: Deploy (Weeks 17-20)\n- UAT\n- Production deployment\n- Knowledge transfer",
      resource_plan: "# Resource Plan\n\n## Team Structure\n| Role | FTE | Duration |\n|------|-----|----------|\n| Project Manager | 1 | 6 months |\n| Solution Architect | 0.5 | 6 months |\n| Data Engineer | 2 | 5 months |\n| BI Developer | 1.5 | 4 months |\n| QA Analyst | 1 | 3 months |",
    },
    {
      opportunity_id: opps[5].id,
      title: "Telstra Network Transformation Phase 2",
      stage: "csd_qualification",
      cas_qualified: "qualified",
      csd_qualified: "pending",
      care_score: 8.5,
      competitive_position: 9,
      attractiveness: 8,
      relationship_strength: 9,
      ease_of_response: 8,
      care_analysis: "Excellent position as incumbent partner on Phase 1. Strong existing relationship with Telstra network team. High attractiveness given multi-year engagement potential. Well-positioned with Cisco/AWS capabilities.",
    },
    {
      opportunity_id: opps[7].id,
      title: "VicPol Data Warehouse Modernisation",
      stage: "writing",
      cas_qualified: "qualified",
      csd_qualified: "qualified",
      bid_manager_id: users[6].id,
      assigned_writer_id: users[5].id,
      care_score: 7.8,
      competitive_position: 7,
      attractiveness: 8,
      relationship_strength: 8,
      ease_of_response: 8,
      care_analysis: "Good competitive positioning with Snowflake partnership. Strong relationship through previous VicPol engagements. Attractive margin opportunity in data analytics space.",
    },
    {
      opportunity_id: opps[9].id,
      title: "BHP Cybersecurity Operations Centre",
      stage: "approved",
      cas_qualified: "qualified",
      csd_qualified: "qualified",
      bid_manager_id: users[2].id,
      assigned_writer_id: users[7].id,
      care_score: 8.2,
      competitive_position: 8,
      attractiveness: 9,
      relationship_strength: 7,
      ease_of_response: 9,
      executive_approval: "approved",
      care_analysis: "Strong security practice with Splunk/CrowdStrike certifications. Highly attractive managed service opportunity with recurring revenue. Good response capability with existing SOC framework templates.",
      technical_response: "# BHP SOC Implementation\n\n## Executive Summary\nReason Group will establish a world-class 24/7 Security Operations Centre for BHP...",
    },
    {
      opportunity_id: opps[6].id,
      title: "NAB Digital Banking Platform Uplift",
      stage: "cas_qualification",
      cas_qualified: "pending",
      csd_qualified: "pending",
    },
    {
      opportunity_id: opps[1].id,
      title: "ACR RFQ DOD WP3 Transition HR Modules",
      stage: "csd_qualification",
      cas_qualified: "qualified",
      csd_qualified: "pending",
      care_score: 6,
      competitive_position: 5,
      attractiveness: 7,
      relationship_strength: 5,
      ease_of_response: 7,
      care_analysis: "Moderate competitive position given Infosys incumbent advantage. Attractive deal value but margin pressure expected. Limited existing relationship. Standard SAP/Oracle response templates available.",
    },
  ]).returning("*");

  await db("workflow_logs").insert([
    { bid_id: bidEntries[0].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[0].id, action: "CAS Qualified", from_stage: "cas_qualification", to_stage: "csd_qualification", performed_by: "Scott Foley" },
    { bid_id: bidEntries[0].id, action: "CSD Qualified", from_stage: "csd_qualification", to_stage: "bid_manager_review", performed_by: "Alex Kocz" },
    { bid_id: bidEntries[0].id, action: "Writer Assigned", from_stage: "bid_manager_review", to_stage: "writing", performed_by: "Mark Volpato" },
    { bid_id: bidEntries[1].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[2].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[2].id, action: "CAS Qualified", from_stage: "cas_qualification", to_stage: "csd_qualification", performed_by: "Mark Volpato" },
    { bid_id: bidEntries[2].id, action: "CSD Qualified", from_stage: "csd_qualification", to_stage: "bid_manager_review", performed_by: "Alex Kocz" },
    { bid_id: bidEntries[2].id, action: "Submitted for Review", from_stage: "writing", to_stage: "executive_review", performed_by: "Anil Kinagi" },
    { bid_id: bidEntries[3].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[3].id, action: "CAS Qualified", from_stage: "cas_qualification", to_stage: "csd_qualification", performed_by: "Scott Foley" },
    { bid_id: bidEntries[4].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[4].id, action: "CAS Qualified", from_stage: "cas_qualification", to_stage: "csd_qualification", performed_by: "Scott Foley" },
    { bid_id: bidEntries[4].id, action: "CSD Qualified", from_stage: "csd_qualification", to_stage: "bid_manager_review", performed_by: "Alex Kocz" },
    { bid_id: bidEntries[4].id, action: "Writer Assigned", from_stage: "bid_manager_review", to_stage: "writing", performed_by: "James Mitchell" },
    { bid_id: bidEntries[5].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[5].id, action: "CAS Qualified", from_stage: "cas_qualification", to_stage: "csd_qualification", performed_by: "Scott Foley" },
    { bid_id: bidEntries[5].id, action: "CSD Qualified", from_stage: "csd_qualification", to_stage: "bid_manager_review", performed_by: "Alex Kocz" },
    { bid_id: bidEntries[5].id, action: "Writer Assigned", from_stage: "bid_manager_review", to_stage: "writing", performed_by: "Mark Volpato" },
    { bid_id: bidEntries[5].id, action: "Submitted for Review", from_stage: "writing", to_stage: "executive_review", performed_by: "Priya Sharma" },
    { bid_id: bidEntries[5].id, action: "Executive Approved", from_stage: "executive_review", to_stage: "approved", performed_by: "Rupa Tamang", notes: "Strong proposal. Approved for submission." },
    { bid_id: bidEntries[6].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[7].id, action: "Bid Created", from_stage: null, to_stage: "cas_qualification", performed_by: "System" },
    { bid_id: bidEntries[7].id, action: "CAS Qualified", from_stage: "cas_qualification", to_stage: "csd_qualification", performed_by: "Aleksandar Vranesevic" },
  ]);

  function generateWeekAllocations(startWeekOffset: number, numWeeks: number, pattern: number[]): string {
    const allocs: Record<string, number> = {};
    const baseDate = new Date();
    baseDate.setDate(baseDate.getDate() - baseDate.getDay() + 1);
    for (let i = 0; i < numWeeks; i++) {
      const weekDate = new Date(baseDate);
      weekDate.setDate(weekDate.getDate() + (startWeekOffset + i) * 7);
      const key = weekDate.toISOString().split("T")[0];
      allocs[key] = pattern[i % pattern.length];
    }
    return JSON.stringify(allocs);
  }

  const jobPlans = await db("job_plans").insert([
    {
      bid_id: bidEntries[0].id,
      title: "Defence Cloud Migration - Job Plan",
      contract_start_date: new Date(),
      forecast_date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
    },
    {
      bid_id: bidEntries[4].id,
      title: "VicPol Data Warehouse - Job Plan",
      contract_start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      forecast_date: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000),
    },
    {
      bid_id: bidEntries[5].id,
      title: "BHP SOC Implementation - Job Plan",
      contract_start_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      forecast_date: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000),
    },
  ]).returning("*");

  await db("job_plan_lines").insert([
    {
      job_plan_id: jobPlans[0].id,
      milestone: "BCG Business Case",
      deliverable: "Cloud readiness assessment",
      resource: "Sarah Chen",
      charge_out_level: "Senior Consultant",
      job_role: "Cloud Architect",
      panel_hourly_rate: 250,
      discount_percent: 10,
      hourly_gross_cost: 95,
      budget_hours: 320,
      forecast_hours: 300,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(0, 8, [100, 100, 80, 80, 50, 50, 20, 20]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[0].id,
      milestone: "BCG Business Case",
      deliverable: "Migration strategy document",
      resource: "Anil Kinagi",
      charge_out_level: "Manager",
      job_role: "Project Manager",
      panel_hourly_rate: 280,
      discount_percent: 5,
      hourly_gross_cost: 110,
      budget_hours: 200,
      forecast_hours: 180,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(0, 10, [50, 50, 80, 80, 80, 80, 50, 50, 20, 20]),
      sort_order: 2,
    },
    {
      job_plan_id: jobPlans[0].id,
      milestone: "Infrastructure Build",
      deliverable: "AWS landing zone setup",
      resource: "James Mitchell",
      charge_out_level: "Senior Consultant",
      job_role: "DevOps Engineer",
      panel_hourly_rate: 240,
      discount_percent: 8,
      hourly_gross_cost: 90,
      budget_hours: 400,
      forecast_hours: 380,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(4, 12, [20, 50, 100, 100, 100, 100, 100, 100, 80, 50, 20, 20]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[0].id,
      milestone: "Infrastructure Build",
      deliverable: "Network & security configuration",
      resource: "Priya Sharma",
      charge_out_level: "Consultant",
      job_role: "Network Engineer",
      panel_hourly_rate: 212.5,
      discount_percent: 0,
      hourly_gross_cost: 80,
      budget_hours: 240,
      forecast_hours: 240,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(6, 8, [80, 100, 100, 100, 100, 80, 50, 20]),
      sort_order: 2,
    },
    {
      job_plan_id: jobPlans[0].id,
      milestone: "Application Migration",
      deliverable: "Application assessment & migration",
      resource: "Scott Foley",
      charge_out_level: "Director",
      job_role: "Migration Lead",
      panel_hourly_rate: 350,
      discount_percent: 15,
      hourly_gross_cost: 140,
      budget_hours: 160,
      forecast_hours: 160,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(8, 12, [20, 50, 50, 80, 80, 80, 80, 50, 50, 20, 20, 20]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[0].id,
      milestone: "Testing & Cutover",
      deliverable: "UAT coordination & go-live support",
      resource: "Mark Volpato",
      charge_out_level: "Senior Manager",
      job_role: "Test Manager",
      panel_hourly_rate: 300,
      discount_percent: 10,
      hourly_gross_cost: 120,
      budget_hours: 120,
      forecast_hours: 120,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(16, 6, [50, 80, 100, 100, 80, 50]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[1].id,
      milestone: "Discovery & Design",
      deliverable: "Current state assessment",
      resource: "Sarah Chen",
      charge_out_level: "Senior Consultant",
      job_role: "Data Architect",
      panel_hourly_rate: 250,
      discount_percent: 5,
      hourly_gross_cost: 95,
      budget_hours: 200,
      forecast_hours: 200,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(0, 6, [100, 100, 80, 80, 50, 20]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[1].id,
      milestone: "Discovery & Design",
      deliverable: "Target architecture design",
      resource: "Anil Kinagi",
      charge_out_level: "Manager",
      job_role: "Solution Architect",
      panel_hourly_rate: 280,
      discount_percent: 10,
      hourly_gross_cost: 110,
      budget_hours: 120,
      forecast_hours: 100,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(1, 5, [50, 80, 80, 50, 20]),
      sort_order: 2,
    },
    {
      job_plan_id: jobPlans[1].id,
      milestone: "Data Migration",
      deliverable: "ETL pipeline development",
      resource: "Priya Sharma",
      charge_out_level: "Consultant",
      job_role: "Data Engineer",
      panel_hourly_rate: 212.5,
      discount_percent: 0,
      hourly_gross_cost: 80,
      budget_hours: 360,
      forecast_hours: 340,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(4, 14, [20, 50, 80, 100, 100, 100, 100, 100, 100, 80, 80, 50, 20, 20]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[2].id,
      milestone: "SOC Foundation",
      deliverable: "SIEM platform deployment",
      resource: "James Mitchell",
      charge_out_level: "Senior Consultant",
      job_role: "Security Engineer",
      panel_hourly_rate: 260,
      discount_percent: 5,
      hourly_gross_cost: 100,
      budget_hours: 280,
      forecast_hours: 260,
      actual_hours: 80,
      weekly_allocations: generateWeekAllocations(-4, 10, [100, 100, 100, 100, 80, 80, 50, 50, 20, 20]),
      sort_order: 1,
    },
    {
      job_plan_id: jobPlans[2].id,
      milestone: "SOC Foundation",
      deliverable: "Playbook development",
      resource: "Priya Sharma",
      charge_out_level: "Consultant",
      job_role: "SOC Analyst",
      panel_hourly_rate: 220,
      discount_percent: 0,
      hourly_gross_cost: 85,
      budget_hours: 200,
      forecast_hours: 200,
      actual_hours: 40,
      weekly_allocations: generateWeekAllocations(-2, 8, [80, 80, 100, 100, 100, 80, 50, 20]),
      sort_order: 2,
    },
    {
      job_plan_id: jobPlans[2].id,
      milestone: "Operational Readiness",
      deliverable: "24/7 shift model setup",
      resource: "Scott Foley",
      charge_out_level: "Director",
      job_role: "Delivery Director",
      panel_hourly_rate: 350,
      discount_percent: 10,
      hourly_gross_cost: 140,
      budget_hours: 80,
      forecast_hours: 80,
      actual_hours: 0,
      weekly_allocations: generateWeekAllocations(4, 6, [20, 50, 50, 80, 50, 20]),
      sort_order: 1,
    },
  ]);

  console.log("Database seeded successfully with test data");
}
